import Link from "next/link"
export const metadata = {
  title: 'Simple application',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body>
        <h1>Simple application</h1>
        <hr />
          <Link href="/">Home</Link>&nbsp;&nbsp;&nbsp;&nbsp;
          <Link href="/users">Users</Link>
        <hr />
        {children}
      </body>
    </html>
  )
}
